version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./db/mydatabase.db:/usr/src/app/mydatabase.db
    environment:
      NODE_ENV: development
    env_file:
      - .env